# Generated by Django 4.0.4 on 2022-06-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAWSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16384)),
            ],
        ),
        migrations.CreateModel(
            name='WrongStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement', models.TextField()),
                ('Set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField()),
                ('Set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset')),
            ],
        ),
    ]
