# Generated by Django 4.0.4 on 2022-06-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.IntegerField()),
                ('Set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset')),
            ],
        ),
    ]
