# Generated by Django 4.0.4 on 2022-06-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0002_binarystatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preceeding_text', models.TextField()),
                ('succeeding_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GapSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAss.gap')),
            ],
        ),
        migrations.CreateModel(
            name='Cloze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAss.gapsolution')),
                ('qaw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset')),
            ],
        ),
    ]
