# Generated by Django 4.0.4 on 2022-06-11 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0002_binarystatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('Categorie', models.CharField(max_length=1024, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='binarystatement',
            old_name='Length',
            new_name='MaxValue',
        ),
        migrations.AddField(
            model_name='qawset',
            name='Set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.categorie'),
        ),
    ]
