# Generated by Django 4.0.4 on 2022-06-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0003_gap_gapsolution_cloze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloze',
            name='gap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAss.gap'),
        ),
    ]
