# Generated by Django 4.0.4 on 2022-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0004_rename_set_qawset_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qawset',
            name='Cat',
        ),
        migrations.AddField(
            model_name='qawset',
            name='Categorie',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
