# Generated by Django 4.0.4 on 2022-06-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0004_alter_cloze_gap'),
        ('EAss', '0005_remove_qawset_cat_qawset_categorie_delete_categorie'),
    ]

    operations = [
    ]
