# Generated by Django 4.0.4 on 2022-06-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0006_merge_20220616_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='Set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
    ]
