# Generated by Django 4.0.4 on 2022-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0008_qawset_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='qawset',
            name='Target',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
