# Generated by Django 4.0.4 on 2022-06-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0009_qawset_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='qawset',
            name='Difficulty',
            field=models.CharField(choices=[('None', 'None'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Insane', 'Insane')], default='None', max_length=24),
        ),
    ]
