# Generated by Django 4.0.4 on 2022-06-25 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0012_remove_qawset_categorie_qawset_itemtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculusSingleUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.IntegerField()),
                ('Correct', models.BooleanField()),
                ('Solved', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
