# Generated by Django 4.0.4 on 2022-07-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0012_remove_qawset_categorie_qawset_itemtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalFormDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_variables', models.IntegerField()),
                ('num_ones', models.IntegerField()),
                ('normal_form', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NormalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.TextField()),
                ('Set', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset')),
                ('normal_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAss.normalformdifficulty')),
            ],
        ),
    ]
