# Generated by Django 4.0.4 on 2022-07-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0013_normalformdifficulty_normalform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalform',
            name='Set',
        ),
        migrations.AlterField(
            model_name='normalformdifficulty',
            name='normal_form',
            field=models.CharField(choices=[('disjunctive', 'disjunctive'), ('conjunctive', 'conjunctive')], max_length=20),
        ),
    ]
