# Generated by Django 4.0.4 on 2022-07-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0013_normalformdifficulty_normalform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qawset',
            name='ItemType',
            field=models.CharField(choices=[('None', 'None'), ('MultipleChoice', 'MultipleChoice'), ('SingleChoice', 'SingleChoice'), ('ClozeText', 'ClozeText'), ('TruthTable', 'TruthTable'), ('Calculus', 'Calculus'), ('Normal Form', 'Normal Form')], default='None', max_length=24),
        ),
    ]
