# Generated by Django 4.0.4 on 2022-07-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0014_alter_qawset_itemtype'),
        ('EAss', '0014_remove_normalform_set_and_more'),
    ]

    operations = [
    ]
