# Generated by Django 4.0.4 on 2022-06-26 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0015_calculussingleuseranswer_calctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAssemblerCodeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('RegisterAnswer', models.TextField()),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
