# Generated by Django 4.0.4 on 2022-07-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0015_merge_20220707_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalform',
            name='Set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
    ]
