# Generated by Django 4.0.4 on 2022-06-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0016_openassemblercodequestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='openassemblercodequestions',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
    ]
