# Generated by Django 4.0.4 on 2022-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0019_openassembleranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='openassemblercodequestions',
            name='NeededInstructions',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
