# Generated by Django 4.0.4 on 2022-07-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0019_rename_num_ones_normalformdifficulty_num_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalformcorrection',
            name='total_points',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='normalformguess',
            name='qaw',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NormalFormKnowledge',
        ),
    ]
