# Generated by Django 4.0.4 on 2022-06-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0020_openassemblercodequestions_neededinstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='openassembleranswer',
            name='MissedStatements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
