# Generated by Django 4.0.4 on 2022-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0021_openassembleranswer_missedstatements'),
    ]

    operations = [
        migrations.AddField(
            model_name='openassemblercodequestions',
            name='CheckNeededInstructions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openassemblercodequestions',
            name='CheckOptimizedSolution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openassemblercodequestions',
            name='OptimizedSolution',
            field=models.TextField(null=True),
        ),
    ]
