# Generated by Django 4.0.4 on 2022-06-29 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0023_alter_openassemblercodequestions_optimizedsolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClozeUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllCorrect', models.BooleanField()),
                ('Solved', models.DateTimeField(default=django.utils.timezone.now)),
                ('Topic', models.CharField(choices=[('None', 'None'), ('Computer-Models', 'Computer-Models'), ('Gates', 'Gates'), ('Calculus', 'Calculus'), ('Optimization', 'Optimization'), ('Assembler', 'Assembler'), ('Quantencomputing', 'Quantencomputing')], default='None', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1024)),
                ('AllCorrect', models.BooleanField()),
                ('Solved', models.DateTimeField(default=django.utils.timezone.now)),
                ('Topic', models.CharField(choices=[('None', 'None'), ('Computer-Models', 'Computer-Models'), ('Gates', 'Gates'), ('Calculus', 'Calculus'), ('Optimization', 'Optimization'), ('Assembler', 'Assembler'), ('Quantencomputing', 'Quantencomputing')], default='None', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=1024)),
                ('Question', models.CharField(max_length=1024)),
                ('Correct', models.BooleanField()),
                ('Solved', models.DateTimeField(default=django.utils.timezone.now)),
                ('Topic', models.CharField(choices=[('None', 'None'), ('Computer-Models', 'Computer-Models'), ('Gates', 'Gates'), ('Calculus', 'Calculus'), ('Optimization', 'Optimization'), ('Assembler', 'Assembler'), ('Quantencomputing', 'Quantencomputing')], default='None', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='TruthTableUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllCorrect', models.BooleanField()),
                ('Solved', models.DateTimeField(default=django.utils.timezone.now)),
                ('Topic', models.CharField(choices=[('None', 'None'), ('Computer-Models', 'Computer-Models'), ('Gates', 'Gates'), ('Calculus', 'Calculus'), ('Optimization', 'Optimization'), ('Assembler', 'Assembler'), ('Quantencomputing', 'Quantencomputing')], default='None', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='SingleTruthTableUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1024)),
                ('Answer', models.CharField(max_length=1024)),
                ('Correct', models.BooleanField()),
                ('AllAnswers', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.truthtableuseranswer')),
            ],
        ),
        migrations.CreateModel(
            name='SingleMultipleChoiceUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=1024)),
                ('Correct', models.BooleanField()),
                ('AllAnswers', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.multiplechoiceuseranswer')),
            ],
        ),
        migrations.CreateModel(
            name='SingleFieldClozeUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpectedAnswer', models.CharField(max_length=1024)),
                ('UserAnswer', models.CharField(max_length=1024)),
                ('Correct', models.BooleanField()),
                ('AllGaps', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.clozeuseranswer')),
            ],
        ),
    ]
