# Generated by Django 4.0.4 on 2022-06-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0024_clozeuseranswer_multiplechoiceuseranswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openassembleranswer',
            name='Topic',
            field=models.CharField(choices=[('None', 'None'), ('Computer-Models', 'Computer-Models'), ('Gates', 'Gates'), ('Calculus', 'Calculus'), ('Optimization', 'Optimization'), ('Assembler', 'Assembler'), ('Quantencomputing', 'Quantencomputing')], default='Assembler', max_length=24),
        ),
        migrations.AddField(
            model_name='singlefieldclozeuseranswer',
            name='Topic',
            field=models.CharField(choices=[('None', 'None'), ('Computer-Models', 'Computer-Models'), ('Gates', 'Gates'), ('Calculus', 'Calculus'), ('Optimization', 'Optimization'), ('Assembler', 'Assembler'), ('Quantencomputing', 'Quantencomputing')], default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='singlemultiplechoiceuseranswer',
            name='Topic',
            field=models.CharField(choices=[('None', 'None'), ('Computer-Models', 'Computer-Models'), ('Gates', 'Gates'), ('Calculus', 'Calculus'), ('Optimization', 'Optimization'), ('Assembler', 'Assembler'), ('Quantencomputing', 'Quantencomputing')], default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='singletruthtableuseranswer',
            name='Topic',
            field=models.CharField(choices=[('None', 'None'), ('Computer-Models', 'Computer-Models'), ('Gates', 'Gates'), ('Calculus', 'Calculus'), ('Optimization', 'Optimization'), ('Assembler', 'Assembler'), ('Quantencomputing', 'Quantencomputing')], default='None', max_length=24),
        ),
    ]
