# Generated by Django 4.0.4 on 2022-06-29 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0024_clozeuseranswer_multiplechoiceuseranswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefieldclozeuseranswer',
            name='Solved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='singlemultiplechoiceuseranswer',
            name='Solved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='singletruthtableuseranswer',
            name='Solved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
