# Generated by Django 4.0.4 on 2022-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0025_openassembleranswer_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openassembleranswer',
            name='OptimizedAnswer',
            field=models.TextField(null=True),
        ),
    ]
