# Generated by Django 4.0.4 on 2022-07-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0026_openassembleranswer_optimizedanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='openassembleranswer',
            name='QuestionID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
