# Generated by Django 4.0.4 on 2022-07-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0025_singlefieldclozeuseranswer_solved_and_more'),
        ('EAss', '0027_openassembleranswer_questionid'),
    ]

    operations = [
    ]
