# Generated by Django 4.0.4 on 2022-07-20 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0028_merge_20220720_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatesAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expectedanswer', models.TextField()),
                ('Answer', models.TextField()),
                ('Solved', models.DateTimeField(default=django.utils.timezone.now)),
                ('Correct', models.BooleanField()),
                ('Topic', models.CharField(choices=[('None', 'None'), ('Computer-Models', 'Computer-Models'), ('Gates', 'Gates'), ('Calculus', 'Calculus'), ('Optimization', 'Optimization'), ('Assembler', 'Assembler'), ('Quantencomputing', 'Quantencomputing')], default='Gates', max_length=24)),
                ('Imgpath', models.CharField(max_length=1024)),
                ('Circuitfunction', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='qawset',
            name='ItemType',
            field=models.CharField(choices=[('None', 'None'), ('MultipleChoice', 'MultipleChoice'), ('SingleChoice', 'SingleChoice'), ('ClozeText', 'ClozeText'), ('TruthTable', 'TruthTable'), ('Calculus', 'Calculus'), ('Assembler', 'Assembler'), ('Gates', 'Gates')], default='None', max_length=24),
        ),
        migrations.CreateModel(
            name='GatesQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Gatesnumber', models.IntegerField()),
                ('Set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset')),
            ],
        ),
    ]
