# Generated by Django 4.0.4 on 2022-07-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0029_gatesanswer_alter_qawset_itemtype_gatesquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatesquestions',
            name='Question',
            field=models.TextField(default='was?'),
            preserve_default=False,
        ),
    ]
