# Generated by Django 4.0.4 on 2022-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0030_gatesquestions_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatesanswer',
            old_name='Circuitfunction',
            new_name='Expectedcircuitfunction',
        ),
        migrations.AddField(
            model_name='gatesanswer',
            name='Answerircuitfunction',
            field=models.CharField(default='test', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gatesanswer',
            name='Answer',
            field=models.BooleanField(),
        ),
    ]
