# Generated by Django 4.0.4 on 2022-07-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0032_alter_gatesanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatesanswer',
            name='Question',
            field=models.TextField(default='was'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gatesanswer',
            name='Answer',
            field=models.PositiveIntegerField(),
        ),
    ]
