# Generated by Django 4.0.4 on 2022-07-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0033_gatesanswer_question_alter_gatesanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatesquestions',
            name='Question',
            field=models.CharField(max_length=1024),
        ),
    ]
