# Generated by Django 4.0.4 on 2022-07-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0028_merge_20220716_0930'),
        ('EAss', '0034_alter_gatesquestions_question'),
    ]

    operations = [
    ]
