# Generated by Django 4.0.4 on 2022-07-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0035_merge_20220721_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GatesQuestions',
        ),
    ]
