# Generated by Django 4.0.4 on 2022-07-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0021_alter_normalformcorrection_total_points'),
        ('EAss', '0035_merge_20220721_1034'),
    ]

    operations = [
    ]
