# Generated by Django 4.0.4 on 2022-07-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0030_merge_20220721_1114'),
        ('EAss', '0036_merge_20220721_1104'),
    ]

    operations = [
    ]
