# Generated by Django 4.0.4 on 2022-07-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0036_delete_gatesquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatesanswer',
            name='Input',
            field=models.CharField(default='a1b0', max_length=1024),
            preserve_default=False,
        ),
    ]
