# Generated by Django 4.0.4 on 2022-07-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0036_merge_20220721_1104'),
        ('EAss', '0037_gatesanswer_input'),
    ]

    operations = [
    ]
