# Generated by Django 4.0.4 on 2022-07-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0038_gatesanswer_userid_singlechoiceuseranswer_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculussingleuseranswer',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculussingleuseranswer',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
        migrations.AddField(
            model_name='clozeuseranswer',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clozeuseranswer',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
        migrations.AddField(
            model_name='gatesanswer',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gatesanswer',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
        migrations.AddField(
            model_name='multiplechoiceuseranswer',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='multiplechoiceuseranswer',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
        migrations.AddField(
            model_name='openassembleranswer',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openassembleranswer',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
        migrations.AddField(
            model_name='singlefieldclozeuseranswer',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlefieldclozeuseranswer',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
        migrations.AddField(
            model_name='singlemultiplechoiceuseranswer',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlemultiplechoiceuseranswer',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
        migrations.AddField(
            model_name='singletruthtableuseranswer',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singletruthtableuseranswer',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
        migrations.AddField(
            model_name='truthtableuseranswer',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truthtableuseranswer',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EAss.qawset'),
        ),
    ]
