# Generated by Django 4.0.4 on 2022-07-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0040_answer_hint_wrongstatements_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletruthtableuseranswer',
            name='Question',
        ),
        migrations.AddField(
            model_name='singletruthtableuseranswer',
            name='Expectedanswer',
            field=models.CharField(default='True', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singletruthtableuseranswer',
            name='Statement',
            field=models.CharField(default='Hallo', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truthtableuseranswer',
            name='Question',
            field=models.CharField(default='Was', max_length=1024),
            preserve_default=False,
        ),
    ]
