# Generated by Django 4.0.4 on 2022-07-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0037_calculussingleuseranswer_duration_and_more'),
        ('EAss', '0041_remove_singletruthtableuseranswer_question_and_more'),
    ]

    operations = [
    ]
