# Generated by Django 4.0.4 on 2022-07-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0038_merge_0036_merge_20220721_1104_0037_gatesanswer_input'),
        ('EAss', '0041_remove_singletruthtableuseranswer_question_and_more'),
    ]

    operations = [
    ]
