# Generated by Django 4.0.4 on 2022-07-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0037_calculussingleuseranswer_duration_and_more'),
        ('EAss', '0042_merge_20220725_1316'),
    ]

    operations = [
    ]
