# Generated by Django 4.0.4 on 2022-07-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0043_merge_20220725_1323'),
        ('EAss', '0043_normalformcorrection_userid_normalformguess_userid'),
    ]

    operations = [
    ]
