# Generated by Django 4.0.4 on 2022-07-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0044_merge_20220725_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalform',
            name='assessment',
            field=models.CharField(choices=[('boolean', 'boolean'), ('grading', 'grading'), ('correcting_boolean', 'correcting_boolean'), ('grading_difference', 'grading_difference'), ('difference', 'difference')], max_length=50),
        ),
    ]
