# Generated by Django 4.0.4 on 2022-07-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0045_alter_normalform_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gap',
            name='Set',
        ),
        migrations.AlterField(
            model_name='gap',
            name='preceeding_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gap',
            name='succeeding_text',
            field=models.TextField(blank=True),
        ),
    ]
