# Generated by Django 4.0.4 on 2022-07-25 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0046_remove_gap_set_alter_gap_preceeding_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalformguess',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='normalformguess',
            name='Solved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
