# Generated by Django 4.0.4 on 2022-07-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0044_merge_20220725_1532'),
        ('EAss', '0047_normalformguess_duration_normalformguess_solved'),
    ]

    operations = [
    ]
