# Generated by Django 4.0.4 on 2022-07-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0047_normalformguess_duration_normalformguess_solved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalformguess',
            old_name='qaw',
            new_name='Set',
        ),
    ]
