# Generated by Django 4.0.4 on 2022-07-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0044_merge_20220725_1444'),
        ('EAss', '0048_rename_qaw_normalformguess_set'),
    ]

    operations = [
    ]
