# Generated by Django 4.0.4 on 2022-07-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0050_normalformguess_allcorrect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qawset',
            name='ItemType',
            field=models.CharField(choices=[('None', 'None'), ('MultipleChoice', 'MultipleChoice'), ('SingleChoice', 'SingleChoice'), ('ClozeText', 'ClozeText'), ('TruthTable', 'TruthTable'), ('Calculus', 'Calculus'), ('Assembler', 'Assembler'), ('Gates', 'Gates'), ('NormalForm', 'NormalForm')], default='None', max_length=24),
        ),
    ]
