# Generated by Django 4.0.4 on 2022-07-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EAss', '0049_merge_20220725_1620'),
        ('EAss', '0051_alter_qawset_itemtype'),
    ]

    operations = [
    ]
